import type { InputType, QueryState } from "@/types/api";

/**
 * lib/storage/history.ts — WS-E owns this module (frontend_plan.md §5.1,
 * "you own the history storage module; another agent was told not to
 * touch it"). Client-side query history: there is no backend for this
 * (plan §2, gap G5 — "Client-side localStorage, no backend change"), so
 * everything here lives in the browser and is lost on
 * `localStorage.clear()` or in a different browser/profile.
 *
 * --- SSR safety ---
 * `localStorage` does not exist during Next.js server rendering or static
 * generation. Every exported function guards `typeof window ===
 * "undefined"` before touching it, degrading to a no-op (writes) or an
 * empty array (reads) instead of throwing — a bare module-level read
 * would break `next build`. Callers must still read inside a `useEffect`
 * rather than during render (see `history-list.tsx`): even though this
 * module itself won't throw on the server, calling `readHistory()` during
 * render would make the server-rendered HTML (necessarily empty) disagree
 * with what the client would paint synchronously on first render, which
 * is a hydration mismatch. Read after mount, not during render.
 *
 * --- Corruption safety ---
 * `readHistory()` never throws. A missing key, invalid JSON, a JSON value
 * that isn't an array, or an array containing entries that don't match
 * the expected shape all degrade to "drop the unreadable parts" — a
 * garbage `localStorage` value must produce an empty (or partial) list,
 * never a white screen.
 *
 * --- Public API (the integration point) ---
 * `addHistoryEntry()` is the one function another workstream's code is
 * expected to call once a `/query` response resolves — see
 * frontend_plan.md WS-E: "the query surface will be wired to call
 * `addHistoryEntry` at integration time by someone else". The intended
 * call, from wherever `POST /query`'s response lands (WS-D's query
 * composer / results surface):
 *
 *   import { addHistoryEntry } from "@/lib/storage/history";
 *
 *   addHistoryEntry({
 *     question: response.question,     // FactCheckedResponse.question
 *     inputType: response.input_type,  // FactCheckedResponse.input_type
 *     state: response.state,           // FactCheckedResponse.state
 *   });
 *
 * It takes only those three fields (frontend_plan.md WS-E: "at minimum
 * the question text, `input_type`, `state`, and when it ran") — `id` and
 * `ranAt` are generated inside `addHistoryEntry` itself so two different
 * callers can never collide on an id or disagree about clock source. Safe
 * to call unconditionally (including, harmlessly, during SSR) — no
 * `typeof window` guard is required at the call site.
 */

/** A single stored history entry — enough to render a row and re-run the query. */
export interface HistoryEntry {
  /** Stable id, generated by `addHistoryEntry`. Never reused after removal. */
  id: string;
  /** The literal text sent as `QueryRequest.question` (a question or a statement). */
  question: string;
  /** Which route `/query` took, from `FactCheckedResponse.input_type`. */
  inputType: InputType;
  /** The route's outcome, from `FactCheckedResponse.state`. */
  state: QueryState;
  /** ISO-8601 timestamp of when the entry was recorded. */
  ranAt: string;
}

/** The fields a caller supplies to `addHistoryEntry`; `id`/`ranAt` are always generated here. */
export type NewHistoryEntry = Pick<HistoryEntry, "question" | "inputType" | "state">;

/** Cap on stored entries (frontend_plan.md WS-E: "50-entry cap with oldest-first eviction"). */
export const HISTORY_LIMIT = 50;

const STORAGE_KEY = "knowrag:history";

const VALID_INPUT_TYPES: readonly InputType[] = ["question", "fact"];
const VALID_STATES: readonly QueryState[] = ["ok", "insufficient_evidence", "contradicted"];

/** Runtime shape guard for one parsed JSON value — the only thing standing
 *  between an arbitrary `localStorage` value and a rendered list. */
function isHistoryEntry(value: unknown): value is HistoryEntry {
  if (value === null || typeof value !== "object") return false;
  const v = value as Record<string, unknown>;
  return (
    typeof v.id === "string" &&
    typeof v.question === "string" &&
    typeof v.ranAt === "string" &&
    typeof v.inputType === "string" &&
    VALID_INPUT_TYPES.includes(v.inputType as InputType) &&
    typeof v.state === "string" &&
    VALID_STATES.includes(v.state as QueryState)
  );
}

function generateId(): string {
  if (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function") {
    return crypto.randomUUID();
  }
  // Fallback for environments without `crypto.randomUUID` (older browsers).
  return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`;
}

/**
 * Reads and validates the stored history, newest-first. Never throws: a
 * missing key, malformed JSON, a non-array value, or individual entries
 * with the wrong shape all degrade gracefully — malformed entries are
 * silently dropped rather than surfacing an error to the caller. Returns
 * `[]` on the server (no `window`) and in any failure case.
 */
export function readHistory(): HistoryEntry[] {
  if (typeof window === "undefined") return [];

  let raw: string | null;
  try {
    raw = window.localStorage.getItem(STORAGE_KEY);
  } catch {
    // Storage inaccessible (private browsing, disabled storage, etc).
    return [];
  }
  if (!raw) return [];

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return [];
  }

  if (!Array.isArray(parsed)) return [];
  return parsed.filter(isHistoryEntry);
}

/** Persists `entries` verbatim, swallowing write failures (quota
 *  exceeded, storage disabled) rather than throwing — a failed write
 *  degrades to "this change wasn't remembered," not a crashed UI. */
function writeHistory(entries: HistoryEntry[]): void {
  if (typeof window === "undefined") return;
  try {
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify(entries));
  } catch {
    // Ignore — see doc comment above.
  }
}

/**
 * Records a new history entry and returns it (with its generated `id` /
 * `ranAt`). Entries are stored newest-first (index 0 is the most recent
 * run); once the list would exceed `HISTORY_LIMIT`, the oldest entries —
 * the tail of the array — are dropped first.
 */
export function addHistoryEntry(entry: NewHistoryEntry): HistoryEntry {
  const full: HistoryEntry = {
    id: generateId(),
    ranAt: new Date().toISOString(),
    ...entry,
  };
  const next = [full, ...readHistory()].slice(0, HISTORY_LIMIT);
  writeHistory(next);
  return full;
}

/** Removes a single entry by id and returns the updated (newest-first)
 *  list. Removing an id that doesn't exist is a no-op. */
export function removeHistoryEntry(id: string): HistoryEntry[] {
  const next = readHistory().filter((entry) => entry.id !== id);
  writeHistory(next);
  return next;
}

/** Clears all stored history. */
export function clearHistory(): void {
  if (typeof window === "undefined") return;
  try {
    window.localStorage.removeItem(STORAGE_KEY);
  } catch {
    // Ignore — see `writeHistory` above.
  }
}
